export { default as DashboardPage } from './DashboardPage'
export { default as HomePage } from './HomePage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as ServicePage } from './ServicesPage'
export { default as DirectoratePage } from './DirectoratePage'
export { default as PostgraduateApplicantsPage } from './PostgraduateApplicantsPage'
