export { default as Loader } from './Loader'
export { default as SocialLinks } from './SocialLinks'
export { default as UniversalLogo } from './UniversalLogo'
export { default as DocumentCard } from './DocumentCard'
export { default as PersonCard } from './PersonCard'
// export { default as PresentationPlayer } from './PresentationPlayer'